### ISSUE TITLE
Bug: resample_model fails with instru_res but not instru_idx

### ISSUE THREAD

**Issue by lwelzel** [VChristiaens/special#4] opened 2023-05-05 16:01 UTC
### Issue
When calling special.model_resampling.resample_model with instru_res given as a float/int but without giving instru_idx (so that instru_idx=None) .utils_spec.find_nearest around line 695 fails since lbda_min is nan.

### Expected behaviour
If all points are from the same instrument supplying instru_idx should not be necessary 

### Suspected cause

lbda_min is nan in this case because in line 680 and following the following is assigned and checked:

```python
  if cond:
      lbda_min = lbda_obs[0]-2*dlbda_obs[0]  # all good here, lbda_min is some float
      if instru_res is not None:  # no check if instru_idx is None
          if np.isscalar(instru_res[0]) and not isinstance(instru_res[0], str):
              lbda_instru = lbda_obs[np.where(instru_idx==1)]  # np.where returns empty array since instru_idx is None
              instru_fwhm = np.mean(lbda_instru)/instru_res[0]  # nan because empty array in np.mean
              lbda_min = lbda_obs[0]-3*instru_fwhm  # nan is assigned to lbda_min
```

Reproduction:
@VChristiaens since you also work on the Exoplanet Data Challenge Project you can reproduce this by running the planet_injection_trainingset.ipynb tutorial for phase2. Fails at step 4. Injection

### Suggested fix:

Include a check for instru_idx is None and/or assign instru_idx as array with all ones if not supplied.

Thanks for the nice library and data challenge.

**Comment by VChristiaens** [comment] 2023-05-08 17:10
Thanks a lot @lwelzel ! I indeed reproduced the bug in the planet_injection_trainingset.ipynb tutorial, and have now fixed it as suggested. I'm a bit puzzled about what broke the intended behaviour, since it used to work fine a couple of sub-versions ago when used to prepare that specific tutorial. Anyway, the fix is now included in the new sub-version that I just released. 

Good luck with the data challenge!

**Closed as completed by VChristiaens** 2023-05-08 17:10 UTC
